-- MySQL Script generated by MySQL Workbench
-- Qua 27 Mai 2015 16:29:07 BRT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema BD_XSAUTH
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema BD_XSAUTH
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BD_XSAUTH` DEFAULT CHARACTER SET utf8 ;
USE `BD_XSAUTH` ;

-- -----------------------------------------------------
-- Table `BD_XSAUTH`.`001_group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_XSAUTH`.`001_group` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) NOT NULL,
  `acronym` VARCHAR(45) NULL,
  `description` TEXT NULL,
  `email` VARCHAR(100) NULL,
  `phone` VARCHAR(15) NULL,
  `address` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD_XSAUTH`.`002_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_XSAUTH`.`002_user` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `001_group_id` BIGINT UNSIGNED NULL,
  `name` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `password` VARCHAR(32) NOT NULL,
  `admin` TINYINT(1) NOT NULL DEFAULT 0,
  `active` TINYINT(1) NOT NULL DEFAULT 1,
  `type` VARCHAR(15) NOT NULL DEFAULT 'visitor',
  `birthdate` DATE NULL,
  `phone` VARCHAR(15) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_002_MEMBER_001_COMPANY_idx` (`001_group_id` ASC),
  CONSTRAINT `fk_002_MEMBER_001_COMPANY`
    FOREIGN KEY (`001_group_id`)
    REFERENCES `BD_XSAUTH`.`001_group` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci
PACK_KEYS = DEFAULT;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
